updated workflow file for building and testing the model

diff --git a/.github/workflows/azure-pipeline.yaml b/.github/workflows/azure-pipeline.yaml
--- a/.github/workflows/azure-pipeline.yaml
+++ b/.github/workflows/azure-pipeline.yaml
@@ -13,11 +13,29 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
+
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
           python-version: '3.x'
+
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -e .
+
+      - name: Run training script
+        run: |
+          python src/azuremlapp/utils/fraud_train.py
+
+      - name: Check pickle file exists
+        run: |
+          if [ -f "outputs/fraud_detection_model.pkl" ]; then
+            echo "Model artifact exists."
+          else
+            echo "Model artifact not found!" && exit 1
+          fi
+
+      - name: Testing: Run scoring script
+        run: |
+          python src/azuremlapp/utils/score.py
